---
Name: SilverStripe-PWA
---

SilverStripe\Control\Director:
  rules:
    'manifest.json': 'SilverStripePWA\Controllers\ManifestController'
    'service-worker.js': 'SilverStripePWA\Controllers\ServiceWorkerController'
    'RegisterServiceWorker.js': 'SilverStripePWA\Controllers\RegisterServiceWorkerController'
    'offline.html': 'SilverStripePWA\Controllers\OfflinePageController'
    'push': 'SilverStripePWA\Controllers\SendPushNotificationController'
    'RegisterSubscription': 'SilverStripePWA\Controllers\RegisterSubscriptionController'
    'pwa-generate-vapid-keys': 'SilverStripePWA\Controllers\GenerateVapidKeysController'
    'pwa-send-test-push': 'SilverStripePWA\Controllers\SendTestPushController'

SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - SilverStripePWA\Extensions\ManifestSiteConfigExtension
        - SilverStripePWA\Extensions\PushNotificationsSiteConfigExtension
        - SilverStripePWA\Extensions\ServiceWorkerSiteConfigExtension
        - SilverStripePWA\Extensions\OfflinePageSiteConfigExtension

# Add the push-extension to the page of your choosing
#
# Example:
# Page:
#     extensions:
#         - SilverStripePWA\Extensions\PushPageExtension
